### ISSUE TITLE
rotate, video display doesnt work from IOS browser

### ISSUE THREAD

**Issue by sixtycycles** [DIYnamics/diyrot#2]
When i use my Iphone 8 to upload a video, the video is not displayed in the mobile browser after selecting it. (this works on a desktop browser)
I have tested this in Duckduckgo browser, Firefox and Safari, and all have the same issue where the image is selected, but the canvas and video element never displays. 

Possibly related: IOS converts the video on my phone before upload. The extension is .MOV, though the same h.264 codec seems to be used. 

If i send the IOS recording to a desktop and try to upload the video that way it also fails to render, though the image display's fine.

**Comment by OrangeRoof** [comment]
Resolved in 4e51c9a286
